### ISSUE TITLE
add index for slug field in article table 

### ISSUE THREAD

**Issue by gouchaoer** [yii2-starter-kit/yii2-starter-kit#470]
in `https://github.com/trntv/yii2-starter-kit/blob/master/common/migrations/db/m140703_123803_article.php`, slug field should use an index

**Comment by gouchaoer** [comment]
this fix has a bug, the 'slug' field is VARCHAR(1024) but InnoDB only allow a max 767 index prefix.

http://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes

so I run into `SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too lo ng; max key length is 767 bytes`

**Comment by trntv** [comment]
There is an issue with column length, so indexes cannot be created. To do so, we should use ``innodb_large_prefix`` or ``dynamic`` row format, but I don't know if it is an appropriate solution for this

**Comment by davidjeddy** [comment]
What about limiting the slug length to 255 characters? While URI CAN be 2048 characters how often does the a single part of a URI exceed 255? Use case VS specs.

**Comment by XzAeRo** [comment]
Considering @davidjeddy comment, and after reading some comments about this specific issue, we will be limiting the slugs up to 255 characters due to the following reasons:

- There's no real benefit for having a 1024 character slug, over a 255 character slug.
- Indexes over 255 characters will be very bulky and inefficient, defeating the purpose of having and index over that field (at least in MySQL).
- Other CMS (Wordpress, Drupal), usually deal with a 200 character limit on their slugs, so it is well known that slugs shouldn't be that much longer.

This will be added as an additional migration that will alter the columns and add the indexes.

**Comment by XzAeRo** [comment]
Fix added under `develop` branch
