### ISSUE TITLE
Frontend, update bootstrap 4

### ISSUE THREAD

**Issue by dungmediabridge** [yii2-starter-kit/yii2-starter-kit#666]

**Comment by kwazaro** [comment]
Is it possible to avoid NPM build tools in new branch? Not all hostings support node.js and java (Yii2 guide for assets management recommends java .jar tools for combining assets). Is there another way to buold frontend scripts remotely (on server side without node)?

**Comment by rivieiraa** [comment]
https://robo.li maybe?

**Comment by rivieiraa** [comment]
https://deployer.org is also a variant to solve problem of not having node available on remote host machine

**Comment by kwazaro** [comment]
The Idea is to have the ability to completely move all development on remote hosting (simple, plain shared hosting without NODE, JAVA and additional software installation, except Composer, Git and access via SSH). Not every project really requires full-stack dev. environment and all that complex things like docker, vagrant etc.

**Comment by XzAeRo** [comment]
> Not every project really requires full-stack dev. environment and all that complex things like docker, vagrant etc.

Completely agree, but most of the current development and production trends are gearing towards virtualization, so including these stuff is kind of necessary, specially for an "starter pack".

Anyway, I agree that NPM/Yarn shouldn't be necessary to build files into production (at least not mandatory). This can be fixed just by including the generated files during development into the bundle folder. Now, should we as `yii2-starter-pack` project force this approach, or let each developer to choose what to do? Maybe just a small documentation about it would be enough.

**Comment by rivieiraa** [comment]
Bootstrap options should be available. Leaving docker and npm type of bootstraping app/assets is a good idea for starter kit. Voting for keeping all the npm and virtualization stuff as is.

**Comment by kwazaro** [comment]
Every developer, perhaps, has his own dev. software on his machine. And everyone can use what he want. But the result should be always the same: folder with assets (images, js, fonts, css) with compiled and minified files. In my development workflow with Yii2 I can do almost everything on remote shared hosting via SSH, EXCEPT frontend processing. I have to use Gulp, because Yii framework has no tools for that. This keeps me to have my local machine with installed NPM, NODE and a lot of other things, which I don't need in most cases. 
I think we should find some PHP library, which can do all that frontend things, like SCSS compiling, concat, minification, image optimization - without any additional software, like Node, Docker etc. And it should be included in Starter kit by default with precompiled frontend files,
Today I tried again to install Yii2 Starter Kit on my hosting and got failed, because of NPM and problems with configuring /backend, /storage, /frontend for single-domain. I think this kit is great, but it will attract more developers, when the installation process will be more convenient and will not require additional specific software.

**Comment by rivieiraa** [comment]
> Is there another way to buold frontend scripts remotely (on server side without node)?
In case you know how to transpile ES6->ES5 and use module system w/o bundler. I guess it's the most popular use case for bundlers these days.

**Comment by XzAeRo** [comment]
Please follow #745 for updates.
