### ISSUE TITLE
Unable to composer to install bshaffer/oauth2-server-php components

### ISSUE THREAD

**Issue by yunfeiboy** [yii2-starter-kit/yii2-starter-kit#674]
Unable to composer to install bshaffer/oauth2-server-php components

**Comment by XzAeRo** [comment]
Well, that library shouldn't be used with Yii2 since it would be mildly redundant (Yii2 itself offers OAuth2 services).

This project template already includes OAuth integration, but if you're feeling lost, please check this usefule guide: https://www.yiiframework.com/wiki/862/yii2-restful-api-with-oauth-2-0
