### ISSUE TITLE
Backend translations manager not found on demo

### ISSUE THREAD

**Issue by victorpdiez** [yii2-starter-kit/yii2-starter-kit#722]
First, thanks for this great job.

Little thing that bothers me is that Backend translations manager are not showing on demo.

Not really important but to me it is one of the strongest point to use your yii2 ;)

**Comment by XzAeRo** [comment]
The backend translations only show up when using the database translations module. By default the project uses file translations instead of the database one, so that's why it shows up empty.

A while ago I tried to hide the translation manager if the database translation module wasn't active, but a lot of people didn't liked that idea. Maybe we will need to find a more elegant solution for that, maybe a flash message.
